name: Tests

on: [push]

jobs:
  Tests:
    runs-on: macos-latest
    steps:
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.1.2'
    - uses: actions/checkout@master
    - name: Run Unit Tests
      run: swift test --enable-code-coverage
    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1.0.5
      with:
        name: Spin.Swift
